# Document: http://goreleaser.com
# This config is for normal release. See .goreleaser-nightly.yml for nightly release.
before:
  hooks:
    - go mod download

builds:
  - env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    main: ./cmd/reviewdog/
    ldflags: -s -w -X github.com/nij4t/reviewdog/commands.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
 
archives:
  - id: main
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md

brews:
  - tap:
      owner: reviewdog
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/nij4t/reviewdog
    description: Automated code review tool integrated with any code analysis tools regardless of programming language.
    test: |
      system "#{bin}/reviewdog -version"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
